// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9PBhE8ZPxKFz2L5OJT-D2lKI4GYqYIeQ',
    appId: '1:956287232988:web:377cb930f7d86724a77d19',
    messagingSenderId: '956287232988',
    projectId: 'aura-5a30c',
    authDomain: 'aura-5a30c.firebaseapp.com',
    storageBucket: 'aura-5a30c.appspot.com',
    measurementId: 'G-6169DSJ11N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAmkftICbIFxK6MKpAUFhtWFtbPC3jPwc',
    appId: '1:956287232988:android:ff2cca9d726b95f9a77d19',
    messagingSenderId: '956287232988',
    projectId: 'aura-5a30c',
    storageBucket: 'aura-5a30c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9_AYSo281lss2VcXSRSORRz3NqhZ9-0w',
    appId: '1:956287232988:ios:1b0d18a6b4feebe5a77d19',
    messagingSenderId: '956287232988',
    projectId: 'aura-5a30c',
    storageBucket: 'aura-5a30c.appspot.com',
    iosBundleId: 'com.example.aura',
  );

}